import os

'''DATABASE'''
CONST_MONGO_URL = os.environ.get('CONST_MONGO_URL')
CONST_DATABASE = os.environ.get('CONST_DATABASE')

'''COLLECTIONS'''
INVENTORY_COUNT_COLLECTION = os.getenv('INVENTORY_COUNT_COLLECTION')